# .readthedocs.yaml
# Read the Docs configuration file
# Build documentation using Sphinx from docs/source/conf.py

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: 3.9
  jobs:
    build:
      type: sphinx

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements.txt
