# Configuration file for the Pandora system
# This file contains the default settings for the system components
# and their parameters.
# Each component is defined with its type and parameters.

database:
  type: "Database"
  db_path: "./data/"
  db_name: "{run_id}.csv"
  lightcurve_name: "{run_id}_lightcurve.npy"

# labjack_ip_address: &labjack_ip_address "169.254.84.89"

monochromator:
  type: "MonochromatorState"
  usb_port: "/dev/tty.usbserial-FTDI1CB2"
  baud_rate: 9600
  timeout: 2
  model: "Acton_SP2150"

labjack:
  ip_address: "169.254.84.89"
  timeout: 2
  shutter: "FIO00"
  flipmount1: "FIO1"
  flipmount2: "FIO2"
  flipmount3: "FIO3"

keysights:
  # Each Keysight device with its own IP address
  K1:
    keysight_ip: "169.254.5.2"
    timeout_ms: 5000
    settings:
      mode: "current"
      range: 1e-9
      nplc: 1.
      nsamples: 100
      delay: 0.
      interval: 2e-3
  K2:
    keysight_ip: "169.254.56.239"
    timeout_ms: 5000
    settings:
      mode: "current"
      range: 1e-9
      nplc: 1.
      nsamples: 100
      delay: 0.
      interval: 2e-3
      
zaber_stages:
  Z1:
    zaber_ip: "192.168.1.70"
    slot_map: {'OD05': 7, 'OD10': 40, 'OD15':2, 'OD20':3, 'Clear':4}
    device_number: 0
    axis_id: 1
    speed_mm_per_sec: 10
  Z2:
    zaber_ip: "192.168.1.70"
    device_number: 1
    axis_id: 1
    speed_mm_per_sec: 10
  Z3:
    zaber_ip: "192.168.1.70"
    device_number: 2
    axis_id: 1
    speed_mm_per_sec: 10

spectrograph:
  type: "SpectrographState"
  usb_port: "/dev/ttyUSB1"   # or "COM4"
  baud_rate: 115200
  timeout: 2

# Additional system parameters
calibration:
  attenuation_file: "/path/to/attenuation_calibration.json"
  pinhole_positions_file: "/path/to/pinhole_positions.json"

logging:
  level: "INFO"
  logfile: "./pandora.log"
