# Configuration file for the Pandora system
# This file contains the default settings for the system components
# and their parameters.
# Each component is defined with its type and parameters.

database:
  type: "Database"
  db_path: "./data/"
  db_name: "{run_id}.csv"
  lightcurve_name: "{run_id}_lightcurve.npy"

# labjack_ip_address: &labjack_ip_address "169.254.84.89"

monochromator:
  usb_port: "/dev/tty.usbserial-FTDI1CB2"
  baudrate: 9600
  # model: "Acton_SP2150"

labjack:
  ip_address: "169.254.84.89"
  timeout: 2
  shutter: "FIO00"
  flipmount1: "FIO1"
  flipmount2: "FIO2"
  flipmount3: "FIO3"

keysights:
  # Each Keysight device with its own IP address
  K1:
    name: "K1"
    keysight_ip: "169.254.5.2"
    timeout_ms: 25000
    settings:
      mode: "CURR"
      rang: 'AUTO'
      nplc: 1.
      nsamples: 10
      delay: 0.
      interval: 2e-3
  K2:
    name: "K2"
    keysight_ip: "169.254.124.255"
    timeout_ms: 25000
    settings:
      mode: "CURR"
      rang: 'AUTO'
      nplc: 1.
      nsamples: 10
      delay: 0.
      interval: 2e-3
      
zaber_stages:
  Z1:
    ip_address: "169.254.47.12"
    slot_map: {'OD05': 7, 'OD10': 46.37, 'OD15': 79.57, 'OD20': 113.57, 'CLEAR': 148.77}
    device: 0
    axis_id: 1
    speed_mm_per_sec: 25
  Z2:
    ip_address: "192.168.1.70"
    device: 1
    axis_id: 1
    speed_mm_per_sec: 10
  Z3:
    ip_address: "192.168.1.70"
    device: 2
    axis_id: 1
    speed_mm_per_sec: 10

spectrograph:
  type: "SpectrographState"
  usb_port: "/dev/ttyUSB1"   # or "COM4"
  baudrate: 115200
  timeout: 2

# Additional system parameters
calibration:
  attenuation_file: "/path/to/attenuation_calibration.json"
  pinhole_positions_file: "/path/to/pinhole_positions.json"

logging:
  level: "INFO"
  logfile: "./pandora.log"
