# Configuration file for the Pandora system
# This file contains the default settings for the system components
# and their parameters.
database:
  type: "pandora.database.db.PandoraDatabase"
  # type: "pandora.database.calib_db.PandoraCalibrationDatabase"
  root: "/Users/pandora_ctrl/Documents/pandoraData/"

monochromator:
  type: "pandora.controller.monochromator.MonochromatorController"
  usb_port: "/dev/tty.usbserial-FTDI1CB2"
  baudrate: 9600
  wav_second_order_filter: 670
  # model: "Acton_SP2150"

labjack:
  ip_address: "169.254.84.89"
  timeout: 2
  flipShutter: "FIO00"
  flipOrderBlockFilter: "FIO6"
  flipOD2First: "FIO2"
  flipOD2Second: "FIO3"
  flipPD2: "FIO5"
  flipQuarterWavePlate: "FIO4"
  # flipPD3: "FIO6"
  
  # Changes to the logic of the flip signals
  # Default is low signal on the beam, high out of the beam
  flipSpecMountInvertLogic: False
  flipOrderBlockFilterInvertLogic: False
  flipOD2FirstInvertLogic: False
  flipOD2SecondInvertLogic: False
  flipPD3InvertLogic: False
  flipQuarterWavePlateInvertLogic: False
  flipPD2InvertLogic: False

keysights:
  type: "pandora.controller.keysight.KeysightController"
  # Each Keysight device with its own IP address
  K1:
    name: "k1"
    keysight_ip: "169.254.5.2"
    timeout_ms: 25000
    settings:
      mode: "CURR"
      rang: 'AUTO'
      nplc: 10.
      nsamples: 50
      delay: 0.
      interval: 2e-3
  K2:
    name: "k2"
    keysight_ip: "169.254.124.255"
    timeout_ms: 25000
    settings:
      mode: "CURR"
      rang: 'AUTO'
      nplc: 10.
      nsamples: 50
      delay: 0.
      interval: 2e-3

zaber_stages:
  type: "pandora.controller.zaberstages.zaberController"
  Z1: # ND Filter
    ip_address: "140.247.113.250"
    # ND filters map
    # The numbers refers to the zaber position in mm
    slot_map: {'ND20': 43.60, 
               'ND15': 78.10, 
               'ND10': 111.50, 
               'ND05': 151.70, 
               'CLEAR': 0.00}
    device: 0
    axis_id: 1
    # Zaber speed in mm/sec
    speed_mm_per_sec: 10
    name: "nd-filter"
  Z2: # Focus SN: 132383 FW: 7.41.17786 
    ip_address: "140.247.113.251"
    device: 0
    axis_id: 1
    speed_mm_per_sec: 10
    # The focus position is given in mm
    # the focus position is very sensitive to positional changes
    slot_map: {'FOCUS': 0.00,
               'P1MM': 18.00,
               'P2MM': 27.80,
               'P3MM': 25.50
    }
    name: "focus"
  Z3: # Pinhole Mask
    ip_address: "140.247.113.252"
    # Pinhole mask map
    # The numbers refers to the zaber position in mm
    # The pinhole mask  with the following configuration:
    # 1. 1mm pinhole
    # 2. 2mm pinhole
    # 3. 3mm pinhole
    slot_map: {'P1MM': 32.65,
               'P2MM': 48.55,
               'P3MM': 16.75,
               'CLEAR': 0.00
               }
    device: 0
    axis_id: 1
    speed_mm_per_sec: 10
    name: "pinhole-mask"

spectrograph:
  type: "pandora.controller.stellarnet.SpectrographController"
  inttime: 1 # ms
  scan_avg: 10
  xtiming: 1 # 1/2 or 3 (low/mid or high resolution) 
  smooth: 1

logging:
  level: "INFO"
  logfile: "./pandora.log"
